import 'reflect-metadata';
import { getMetadataArgsStorage } from 'typeorm';
import { Recommendation } from './recommendation.entity';

describe('Recommendation', () => {
  it('should be defined', () => {
    expect(Recommendation).toBeDefined();
  });

  it('should create a Recommendation instance', () => {
    const recommendation = new Recommendation();

    recommendation.id = 'rec_123';
    recommendation.type = 'REVIEW';
    recommendation.action = 'Review transaction';
    recommendation.reason = 'Transaction has elevated risk';
    recommendation.risk_score = 0.85;
    recommendation.status = 'pending';
    recommendation.created_at = '2026-09-05T10:30:00Z';

    expect(recommendation).toBeInstanceOf(Recommendation);
    expect(recommendation.id).toBe('rec_123');
    expect(recommendation.type).toBe('REVIEW');
    expect(recommendation.action).toBe('Review transaction');
    expect(recommendation.reason).toBe('Transaction has elevated risk');
    expect(recommendation.risk_score).toBe(0.85);
    expect(recommendation.status).toBe('pending');
    expect(recommendation.created_at).toBe('2026-09-05T10:30:00Z');
  });

  it('should have the recommendations table entity metadata', () => {
    const table = getMetadataArgsStorage().tables.find(
      (metadata) => metadata.target === Recommendation,
    );

    expect(table).toBeDefined();
    expect(table?.name).toBe('recommendations');
  });

  it('should define the expected columns', () => {
    const columns = getMetadataArgsStorage().columns
      .filter((metadata) => metadata.target === Recommendation)
      .map((metadata) => metadata.propertyName);

    expect(columns).toEqual(
      expect.arrayContaining([
        'id',
        'type',
        'action',
        'reason',
        'risk_score',
        'status',
        'created_at',
      ]),
    );
  });

  it('should configure id as a primary column', () => {
    const column = getMetadataArgsStorage().columns.find(
      (metadata) =>
        metadata.target === Recommendation &&
        metadata.propertyName === 'id',
    );

    expect(column).toBeDefined();
    expect(column?.mode).toBe('regular');
  });

  it('should configure risk_score as a real column', () => {
    const column = getMetadataArgsStorage().columns.find(
      (metadata) =>
        metadata.target === Recommendation &&
        metadata.propertyName === 'risk_score',
    );

    expect(column).toBeDefined();
    expect(column?.options.type).toBe('real');
  });

  it('should configure status with pending as the default', () => {
    const column = getMetadataArgsStorage().columns.find(
      (metadata) =>
        metadata.target === Recommendation &&
        metadata.propertyName === 'status',
    );

    expect(column).toBeDefined();
    expect(column?.options.default).toBe('pending');
  });

  it('should configure the expected column types', () => {
  const expectedTypes: Record<string, string | Function> = {
    id: String,
    type: String,
    action: String,
    reason: String,
    risk_score: 'real',
    status: String,
    created_at: String,
  };

  for (const [field, expectedType] of Object.entries(expectedTypes)) {
    const column = getMetadataArgsStorage().columns.find(
      (metadata) =>
        metadata.target === Recommendation &&
        metadata.propertyName === field,
    );

    expect(column).toBeDefined();
    expect(column?.options.type).toBe(expectedType);
  }
});

  it('should not configure an autogenerated id', () => {
    const generation = getMetadataArgsStorage().generations.find(
      (metadata) =>
        metadata.target === Recommendation &&
        metadata.propertyName === 'id',
    );

    expect(generation).toBeUndefined();
  });
});