import 'reflect-metadata';
import { getMetadataArgsStorage } from 'typeorm';
import { Transaction } from './transaction.entity';

describe('Transaction', () => {
  it('should be defined', () => {
    expect(Transaction).toBeDefined();
  });

  it('should create a Transaction instance', () => {
    const transaction = new Transaction();

    transaction.id = 'txn_123';
    transaction.amount = 1500.5;
    transaction.currency = 'USD';
    transaction.vendor = 'Amazon';
    transaction.timestamp = '2026-09-05T10:30:00Z';
    transaction.category = 'shopping';
    transaction.counterparty_id = 'vendor_123';

    expect(transaction).toBeInstanceOf(Transaction);
    expect(transaction.id).toBe('txn_123');
    expect(transaction.amount).toBe(1500.5);
    expect(transaction.currency).toBe('USD');
    expect(transaction.vendor).toBe('Amazon');
    expect(transaction.timestamp).toBe('2026-09-05T10:30:00Z');
    expect(transaction.category).toBe('shopping');
    expect(transaction.counterparty_id).toBe('vendor_123');
  });

  it('should have the transactions table entity metadata', () => {
    const table = getMetadataArgsStorage().tables.find(
      (metadata) => metadata.target === Transaction,
    );

    expect(table).toBeDefined();
    expect(table?.name).toBe('transactions');
  });

  it('should define the expected columns', () => {
    const columns = getMetadataArgsStorage().columns
      .filter((metadata) => metadata.target === Transaction)
      .map((metadata) => metadata.propertyName);

    expect(columns).toEqual(
      expect.arrayContaining([
        'id',
        'amount',
        'currency',
        'vendor',
        'timestamp',
        'category',
        'counterparty_id',
      ]),
    );
  });

  it('should configure id as a text primary column', () => {
    const column = getMetadataArgsStorage().columns.find(
      (metadata) =>
        metadata.target === Transaction &&
        metadata.propertyName === 'id',
    );

    expect(column).toBeDefined();
    expect(column?.options.type).toBe('text');
    expect(column?.mode).toBe('regular');
  });

  it('should configure amount as a real column', () => {
    const column = getMetadataArgsStorage().columns.find(
      (metadata) =>
        metadata.target === Transaction &&
        metadata.propertyName === 'amount',
    );

    expect(column).toBeDefined();
    expect(column?.options.type).toBe('real');
  });

  it('should use text columns for string fields', () => {
    const textFields = [
      'currency',
      'vendor',
      'timestamp',
      'category',
      'counterparty_id',
    ];

    for (const field of textFields) {
      const column = getMetadataArgsStorage().columns.find(
        (metadata) =>
          metadata.target === Transaction &&
          metadata.propertyName === field,
      );

      expect(column).toBeDefined();
      expect(column?.options.type).toBe('text');
    }
  });

  it('should not configure an autogenerated id', () => {
    const generation = getMetadataArgsStorage().generations.find(
      (metadata) =>
        metadata.target === Transaction &&
        metadata.propertyName === 'id',
    );

    expect(generation).toBeUndefined();
  });
});